/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ejercicio2_antt;

import java.util.Scanner;

public class App {

	boolean asientos[] = new boolean[10];
	boolean llenoEconomico = false;
	boolean llenoCaro = false;
	Scanner con = new Scanner(System.in);

	public void app() {
		// menu principal
		int eleccion = 0;
		while (true) {
			// preguntar la eleccion
			System.out.println("Elija una opcion:");
			System.out.println("1- Primera clase");
			System.out.println("2- Clase turista");
			System.out.println("69- salir");
			System.out.print(">> ");
			try {
				eleccion = Integer.parseInt(con.nextLine());
			} catch (Exception e) {
				System.out.println("Valor invalido o error del sistema");
			}

			// realizar la carga del pasaje
			if (eleccion == 1) {
				pasajePrimeraClase();
			} else if (eleccion == 2) {
				pasajeEconomico();
			} else if (eleccion == 69) {
                System.exit(0);
            }
		}
	}

	private void pasajePrimeraClase() {
		int i = 0;
		// buscar el asiento disponible
		while (i < 5) {
			// asiento libre
			if (!asientos[i]) {
				System.out.println("\nPrimera Clase \tAsiento: " + (1 + i)
				    + "\n");
				asientos[i] = true;
				return;
			}
			i++;
		}
		llenoCaro = true;
		cambioPasaje(" clase economica", 2);
	}

	private void pasajeEconomico() {
		int i = 5;
		// buscar el asiento disponible
		while (i < 10) {
			// buscar un asiento libre
			if (!asientos[i]) {
				System.out.println("\nClase economica \tAsiento: " + (1 + i)
				    + "\n");
				asientos[i] = true;
				return;
			}
			i++;
		}
		// si no lo encuentra marcar como seccion llena y preguntar el cambio
		llenoEconomico = true;
		cambioPasaje(" primera clase", 1);
	}

	private void cambioPasaje(String cambio, int e) {
		// si es que alguna de las dos tiene espacio preguntar por el cambio
		if (!llenoCaro || !llenoEconomico) {
			// preguntar al usuario si es que desea realizar el cambio de asiento
			System.out.println("La seccion se encuentra llena. \nAcepta ser asignado a la" + cambio + " ?");
			System.out.println("1- Si");
			System.out.println("2- No");
			System.out.print(">> ");

			int eleccion;
			try {
				eleccion = Integer.parseInt(con.nextLine());
			} catch (Exception x) {
				System.out.println("Valor invalido o error del sistema");
				return;
			}

			// si el usuario elige que "no", entonces no hacer nada
			if (eleccion == 2) {
				return;
			}

			// en todo caso realizar el cambio de pasaje
			if (e == 1) {
				pasajePrimeraClase();
			} else {
				pasajeEconomico();
			}
		} else {
			System.out
			    .println("Lo sentimos, ya no quedan asientos disponibles.\n El siguiente vuelo sale en 3 horas\n");
		}
	}

	// main del programa
	public static void main(String[] args) {
		// iniciar el programa
		new App().app();
	}
}
